# _config.yaml

url: https://www.cis.upenn.edu
baseurl: ~fbrett

browserify:

  # target exts to convert
  exts: [".js"]
  
  # use installed 'browserify'
  command: "browserify -"
  
  # execute `npm install` on initialize if true
  npm_install: false
  
  # set nvm properties if you want to use with nvm installed automatically
  nvm:
    
    # required modules
    modules: [web3]
    
    # browserify option string
    option: ""
    
    # node version if you specify, or use '.nvmrc' if 'null'
    node_version: null
