theme: jekyll-theme-minimal
title: Brett Hemenway Falk
description: Brett Hemenway Falk is a cryptography at the University of Pennsylvania
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - publications.md
  - README.md
  - students.md

